### ISSUE TITLE
ProcessChangelogHooks: SQLSTATE[HY000]: General error: 1093 You can't specify target table 'process_changelog' for update in FROM clause

### ISSUE THREAD

**Issue by matjazpotocnik** [teppokoivula/ProcessChangelog#38] opened 2023-08-21 14:38 UTC
This error was issued when I pruned the log. Settings I used:

![image](https://github.com/teppokoivula/ProcessChangelog/assets/7663992/f6963d29-9d05-4e25-b7fa-b22f958f112a)

**Comment by teppokoivula** [comment] 2023-08-26 14:41
This should be fixed in version 1.15.2, though please let me know if it still persists :)

I couldn't reproduce the error in my environment, so it appears to depend on MySQL version or configuration, but I did figure out what was likely causing this.

**Closed** 2023-08-28 12:32 UTC
