### ISSUE TITLE
Duplicate column name error

### ISSUE THREAD

**Issue by eladnova** [teppokoivula/ProcessChangelog#7] opened 2015-04-09 11:31 UTC
Just installed this on a 2.5.2 site and had following error

Error: Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'templates_id' (in /var/www/vhosts/mydomain.com/httpdocs/wire/core/WireDatabasePDO.php line 191)
This error message was shown because you are logged in as a Superuser. Error has been logged.

It was a 2.5.25 or 2.5.24 install.

I can reproduce the error on another test site running same version of PW.

**Comment by eladnova** [comment] 2015-04-09 11:34
I can fix the error by manually removing the following tables from the database

process_changelog
modules > ProcessChangelog

**Comment by teppokoivula** [comment] 2015-04-18 12:21
Looks like the switch to PDO introduced an issue to the `updateDatabaseSchema()` method. PDO::exec returns number of rows affects, which at this point can be 0, while earlier implementation (mysqli::query) returned boolean for this type of query.

If you've already installed the module, the easiest method is altering the code, uninstalling, and then reinstalling -- or manually updating the schema version in the modules table (class = "ProcessChangelogHooks").

Sorry for the inconvenience!

**Comment by adrianbj** [comment] 2015-04-21 19:56
Hey teppo - this doesn't actually seem to work for me. I am still getting the error. It is still executing the:
```
$this->database->exec($sql)
```
which is the problem.

**Comment by teppokoivula** [comment] 2015-04-22 03:54
@adrianbj just checking, but does it do this even on a clean install -- i.e. not on a site where the module was installed while the issue still existed? Or, if this is a site where you had this issue before, did you remove both the ProcessChangelog and ProcessChangelogHooks modules before trying again?

If the schema version is incremented, this shouldn't happen, so this sounds like it's *not* being incremented properly.. which is something I can't reproduce here anymore. Either that, or there's some leftover stuff in the database :)

**Comment by adrianbj** [comment] 2015-04-22 04:15
Sorry, I took another look at got it sorted. I thought I had deleted all the relevant DB entries, but did a more thorough search through, got them all and now it is working again. Not actually positive in the PW install had Changelog installed previously or not, but I think it might. Anyway I tested on a clean install and it worked fine and I have my site working now also, so I think it's all ok, although there might be some tricky updating in some situations for other users.

Sorry, please go ahead and close this again!

**Comment by teppokoivula** [comment] 2015-04-22 07:02
Thanks for taking another look at this! I'm closing the issue for now, but you're right in that this might still affect some users. Luckily the issue was there for a relatively short amount of time, and only affected new installations, so hopefully no big harm done :)

**Closed by teppokoivula** 2015-04-22 07:02 UTC
