### ISSUE TITLE
2.6 compatible?

### ISSUE THREAD

**Issue by eladnova** [teppokoivula/ProcessChangelog#10] opened 2015-06-03 09:53 UTC
Hi Teppo

Is this Module compatible with 2.6X?

When I add the Module, the Install button doesn't seem to have any effect and remains grey.

Oddly enough, there is a ChangeLog page under the Setup tab and clicking it displays the following.

This page has no Process assigned.

**Comment by teppokoivula** [comment] 2015-06-03 09:59
Sounds weird. Thanks for reporting this; not entirely sure if I've used this module on any 2.6 sites yet, so can't be anything 100% certain about compatibility :)

**Comment by eladnova** [comment] 2015-06-03 10:05
You're welcome.
It's one of my must-have Modules so I'm running it on all my 2.6 installs. Or rather, trying to run it :)

**Comment by eladnova** [comment] 2015-06-12 10:11
Hi Teppo. Any 2.6 love for this? 
Getting errors as follows and unable to install on other 2.6 installs

Unable to install module 'ProcessChangelog': SQLSTATE[23000]: Integrity constraint violation: 1062... 11 secs 
Unable to install module 'ProcessChangelog': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'changelog-22' for key 'name_parent_id'

**Comment by teppokoivula** [comment] 2015-06-12 11:58
Sorry. This has been on the back burner, wanted to get next version of my version control module out first. I'll try to devote a few moments to changelog this weekend!

**Comment by eladnova** [comment] 2015-06-12 12:01
No rush. Just wondering.
Don't give up your weekend fun :)

**Comment by teppokoivula** [comment] 2015-07-03 18:01
@eladnova Took me a while to get here, but after testing this on 2.6, I'm not able to reproduce the issue you've described here. 

The "duplicate entry 'changelog-22' for key 'name_parent_id'" is an issue with the pages database table, and means that the Setup > Changelog pages already exists. Installing the module adds this page, or attempts to do so, and fails because the page already exists.

As for *why* it already exists, this sounds like a result of a previously interrupted or failed installation. When you say that "When I add the Module, the Install button doesn't seem to have any effect and remains grey", I'm mostly curious about how exactly this happened -- can you describe the exact steps you took to fetch and install this module? Did you download/clone the module and install manually, or use Modules Manager, or perhaps the built-in module download and install system?

The easiest way to clean this error and restart the installation would be removing manually the Setup > Changelog page via Page Tree. The module could do this too, but the thing is that someone might've added such a page there intentionally, and I don't want to accidentally overwrite anything. This would require additional checks, at the very least.

**Comment by eladnova** [comment] 2015-07-21 16:25
Hi Teppo

Im not sure exactly how I originally installed ProcessChangelog. It was some time ago.
Suspect it was directly via the admin and by searching for the Module by key.

I just manually removed the Setup>Changelog page and I get an error now:

Error: Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'theprimaryplan.process_changelog' doesn't exist (in /var/www/vhosts/theprimaryplanet.ie/httpdocs/wire/core/WireDatabasePDO.php line 191)

I'll try to somehow restore that to at least get back to a working site.

**Comment by eladnova** [comment] 2015-07-21 16:51
Quick update. Removing the module via the database restores the site to a functioning state.
There was a database reference too to ChangeLog Hooks or similar which I removed.

Once I'd done that and reinstalled the Module (via ZIP upload), the Module now works. Thanks Teppo. :)

**Comment by teppokoivula** [comment] 2015-07-21 17:18
Glad to hear you got it working, and sorry you had to go through such a hassle to get it running again :)

I'm closing this issue for now. Haven't been able to reproduce this, so unless the same issue appears again, it probably was an interrupted install or something similar.

**Closed by teppokoivula** 2015-07-21 17:18 UTC
Labels: Can't Reproduce, Needs More Information, Potential Bug
